### ISSUE TITLE
[Q] Output folder/file

### ISSUE THREAD

**Issue by vavavr00m** [poynty/ArkGollum#1] opened 2023-06-18 01:08 UTC
Where is the output folder and what is the name & extension of the output? There's no option to set output dir currently and no output file was generated in the directory the executable is in. All it said was "Gollum has searched in 100% of folders and has found some precious in 14% of those folders."

**Comment by poynty** [comment] 2023-06-18 01:12
Output is in the respective mod folders, 1 per mod folder in the format \<modname\>_\<modID\>.txt             

Will add -o --output option.

**Comment by poynty** [comment] 2023-06-18 01:47
Update with output option pushed.

**Comment by vavavr00m** [comment] 2023-06-18 10:28
-o worked and I also found the previous result. Both outputs have double slashes between ShooterGame & Game in any spawncode format with it. I know you said it's only for Mods for now but it produced results for Primitive Plus and I thought you should know.

Item Spawncode:
`admincheat GiveItem "Blueprint'/Game/Mods/111111111/ShooterGame//Game/Mods/APS/Blueprints/PrimalItemStructure_Mailbox.PrimalItemStructure_Mailbox'" 1 1 0`

Creature Spawncode:
`admincheat SpawnDino "Blueprint'/Game/Mods/111111111/ShooterGame//Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP'" 500 0 0 120`

S+ Pull Resources:
`PullResourceAdditions=/Game/Mods/111111111/ShooterGame//Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_BirthdayCandle.PrimalItemResource_BirthdayCandle`

Simple Spawners:
`Blueprint'/Game/Mods/111111111/ShooterGame//Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP'`

**Comment by poynty** [comment] 2023-06-18 12:39
I had to grab Primitive Plus, can reproduce the problem, turns out Primitive Plus counts as a mod and is in the mod folder. Will have to make some kind of special case ability to handle its non standard folder layout and any future ones. Is it only primitive plus you are experiencing the // error in?

**Comment by vavavr00m** [comment] 2023-06-18 13:39
Yes but I only have vanilla stuff installed now. When I add other mods again, I will check and let you know if I get the same error.

**Comment by poynty** [comment] 2023-06-18 23:26
Pushed a fix for the // issue.

**Comment by vavavr00m** [comment] 2023-06-19 10:28
Awesome. Gonna check after the 100 mods are installed.. It's been installing for an hour...

**Comment by vavavr00m** [comment] 2023-06-20 20:30
Took a while because, apparently, adding a flag `-TotalConversionMod=111111111` to launch options prevented the mods from installing. It was only today that I had thought of removing it. Can confirm the double slash issue has been fixed with the latest update.

Extremely happy with the speed of ArkGollum - it scanned all the mod folders & subfolders (about 115 mods) in less than a minute! The spawncodes for Primitive Plus weren't working in the previous version. Haven't been able to re-check because it's still loading... Will revert to you asap.

Two things:

1. 115 (114 mods + Primitive Plus) is the expected no. of txt files but only 109 files are in the output folder. It will help to track down those mods if ArkGollum can print a list of mods without a txt output.
2. S+ Pull Resources & Simple Spawners have a space between the header and the spawncodes.

**Comment by poynty** [comment] 2023-06-21 20:51
I have pushed an update that adds the -l option to the command, if specified Gollum will output to console a list of directories where no codes were found. Not sure if this or to a file is the better method. Thoughts?

**Comment by vavavr00m** [comment] 2023-06-22 21:05
After trying for days, Primitive Plus finally loaded. It's such a pain. Does Primitive Plus work with mods? BTW, the spawncodes are working now.

With regards to the directories where ArkGollum found no traces of "precious", I used -l at first but it was invalid and switched it to -f when I saw the commit message. It is preferrable to have it output to a file but perhaps someone will find it also useful to only output to console.. How about two different options? And also, it will be even more helpful to have it also include the Steam workshop link and mod name.. Anyway, I checked the links and the mods without "precious" found are:
[Very Flat Map](https://steamcommunity.com/sharedfiles/filedetails/?id=2041231763) - map, not expecting spawncode
[Flat Map Custom](https://steamcommunity.com/sharedfiles/filedetails/?id=2048452212) - map, not expecting spawncode
[Custom Baby Maturation Speed](https://steamcommunity.com/sharedfiles/filedetails/?id=2843815695) - expecting an engram, a consummable item "Baby speed booster", some others (I see skins & chibis but not sure what they are for)?
[Better Mutagen Spawns](https://steamcommunity.com/sharedfiles/filedetails/?id=2848821611) - expecting 3 additional seeds,  some others (I see skins & chibis but not sure what they are for)?
[BetterPVE](https://steamcommunity.com/sharedfiles/filedetails/?id=2903548924) - addit'l events, not expecting spawncode
[Configurable Boss Arena + Genesis](https://steamcommunity.com/sharedfiles/filedetails/?id=2946668855) - there are stuff in the subfolders that "could" be spawnables..

Yet to test S+ Pull Resources & SimpleSpawners codes because Primitive+ couldn't run with mods or it's taking a lot longer than expected that Steam crashes before it completely loads.

Can you separate ArkOmega spawncodes (path ends in AO) from Zytharian Creatures and add a note saying that it wouldn't show up in-game if ArkOmega is not used - I only saw that in the comments section of Zytharian Creatures.

**Comment by poynty** [comment] 2023-06-23 01:29
Hi, can you clarify what you mean with "Can you separate ArkOmega spawncodes (path ends in AO) from Zytharian Creatures and add a note saying that it wouldn't show up in-game if ArkOmega is not used - I only saw that in the comments section of Zytharian Creatures." I don't quite understand.

**Comment by vavavr00m** [comment] 2023-06-23 10:06
To separate them as in:

-----Creature Spawncodes-----
```
admincheat SpawnDino "Blueprint'/Game/Mods/1754846792/Creatures/Robot_Anky/Ankylo_Character_BP_Robot.Ankylo_Character_BP_Robot'" 500 0 0 120
admincheat SpawnDino "Blueprint'/Game/Mods/1754846792/Creatures/Robot_Bary/Baryonyx_Character_BP_Robot.Baryonyx_Character_BP_Robot'" 500 0 0 120
admincheat SpawnDino "Blueprint'/Game/Mods/1754846792/Creatures/Robot_Deinon/Deinonychus_Character_BP_Robot.Deinonychus_Character_BP_Robot'" 500 0 0 120
```

-----Creature Spawncodes for ArkOmega creatures in Zytharian Creatures----
```
admincheat SpawnDino "Blueprint'/Game/Mods/1754846792/AO/Ankylo_Character_BP_Robot_AO.Ankylo_Character_BP_Robot_AO'" 500 0 0 120
admincheat SpawnDino "Blueprint'/Game/Mods/1754846792/AO/Baryonyx_Character_BP_Robot_AO.Baryonyx_Character_BP_Robot_AO'" 500 0 0 120
admincheat SpawnDino "Blueprint'/Game/Mods/1754846792/AO/Bee_Queen_Character_BP_Skeletal_AO.Bee_Queen_Character_BP_Skeletal_AO'" 500 0 0 120
```

**Comment by poynty** [comment] 2023-06-23 18:21
Pushed an update which should do that hopefully

**Comment by vavavr00m** [comment] 2023-06-23 19:32
That fixes the ArkOmega thing. Thanks.

ArkGollum isn't picking up anything from [Custom Baby Maturation Speed](https://steamcommunity.com/sharedfiles/filedetails/?id=2843815695) & [Better Mutagen Spawns](https://steamcommunity.com/sharedfiles/filedetails/?id=2848821611). Here's the [mods dir list](https://mega.nz/file/XQElADZI) in case needed.

Decrypt: kQuLB3CxYqgCXjeB2JO_lc2nQecmeSsdeAGlMpaAPRg

**Comment by poynty** [comment] 2023-06-24 13:18
OK so with Custom Baby Maturation Speed it uses non-standard naming conventions so fails to be detected as a valid mod. I have fixed this but would prefer to find a better way to validate mods, this will come later. I will check the other one later.

I have also added -l to options to allow you to specify the level of the creature generated by the spawn codes. This is why the other option wasn't l as I had this in mind before hand.

**Comment by vavavr00m** [comment] 2023-07-01 01:20
I see.

1. I see a file called "Engram_BabySpeed.uasset" in [Custom Baby Maturation Speed](https://steamcommunity.com/sharedfiles/filedetails/?id=2843815695), isn't that supposed to be an engram? ArkGollum didn't list it in the Engrams but Items spawncodes are listed now. 

2. [Better Mutagen Spawns](https://steamcommunity.com/sharedfiles/filedetails/?id=2848821611) item spawncodes are listed now.

3. ArkGollum is producing a txt file for the following but it's empty (as in no engram or spawncodes):

![image](https://github.com/poynty/ArkGollum/assets/4675132/77c6d2ae-177d-4b4f-ba45-cb2315e2ccf2)

- AE_PF_Compatability_1979296691
- AEPFCompat2_2859421037
- Ark-Nucleus_2566418613
- BetterHordeMode_2112042937
- BetterPVE_2903548924
- CrystalClear_845781509
- CustomDinoLoot_2493509767
- CustomHarvesting_2021297623
- DinoLevelupFinder_2097526040
- DinoScanner_1591643730
- EggWiper_2836229588
- Inventory_Saver_2623890618
- RandomConfigs_2541512967
- SafeOSDVeins_2123441424
- ScheduledDinoWipe_1438271117
- SGUI_2867471723

**Comment by poynty** [comment] 2023-07-01 01:55
Thanks, will look into those and update with a fix.

**Comment by poynty** [comment] 2023-07-06 19:04
Pushed update, the issue was the mods of these I checked have no spawnable items or creatures. Gollum no checks for this and doesn't create a file for these mods and instead lists them as ones that produce no precious. A "NoPrecious.txt" file is now created if you specify the option which details which mods have no output.

If you get more issues or feature requests please open a new one, I will close this issue for now.

**Closed as completed by poynty** 2023-07-06 19:05 UTC
